name: KillStreak
main: com.jackwilsdon.killstreak.KillStreakPlugin
version: ${project.version}
description: "Get potion effects for kill streaks!"
author: "Jack Wilsdon (jackwilsdon)"
website: "http://dev.bukkit.org/bukkit-plugins/killstreak/"

commands:
    killstreak:
        description: View your current kill streak
        usage: /killstreak
        aliases: ["ks"]
